import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

export default function Home({ videoList }: any) { // TODO: 型別
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* {videoList && videoList.length ? videoList[1].id : ''} */}
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://us-central1-lithe-window-713.cloudfunctions.net/frontendQuiz`)
  const data = await res.json()
  const videoList = data.status ? data.data : [];

  return { props: { videoList } }
}
