import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import VideoList from '@/components/VideoList'

export default function Home({ videoList }: any) { // TODO: 型別
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet" />
			</Head>
			<main className={styles.main}>
				<VideoList videoList={videoList} />
			</main>
		</>
	)
}

export async function getServerSideProps() {
	const res = await fetch(`https://us-central1-lithe-window-713.cloudfunctions.net/frontendQuiz`)
	const data = await res.json()
	const videoList = data.status ? data.data : [];

	return { props: { videoList } }
}
